github.com:
    users:
        Tar-ive:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Tar-ive
