#!/bin/bash

echo "🧠 Gmail Setup - Simple OAuth Playground Method"
echo "==============================================="
echo ""
echo "Since you got a redirect_uri_mismatch error, let's use the simpler approach:"
echo ""
echo "SIMPLE METHOD (No custom credentials needed):"
echo "--------------------------------------------"
echo "1. Go to: https://developers.google.com/oauthplayground/"
echo ""
echo "2. DON'T change any settings - use defaults"
echo ""
echo "3. In the left panel, scroll down to 'Gmail API v1'"
echo ""
echo "4. Check: https://www.googleapis.com/auth/gmail.modify"
echo ""
echo "5. Click 'Authorize APIs' and sign in"
echo ""
echo "6. Click 'Exchange authorization code for tokens'"
echo ""
echo "7. Copy the 'Access token' (starts with ya29...)"
echo ""
echo "8. Save it:"
echo "   /Users/tarive/brain/commands/brain gmail-token 'YOUR_TOKEN_HERE'"
echo ""
echo "This token will work for 1 hour. For permanent access, also copy the"
echo "'Refresh token' and we can set up automatic renewal later."
echo ""
echo "The OAuth Playground uses Google's verified credentials, so no redirect"
echo "URI issues!"
echo ""

# Also provide instructions for updating credentials if they want to fix it
echo "ALTERNATIVE: Fix Your Credentials (Advanced)"
echo "--------------------------------------------"
echo "If you want to use your own credentials, you need to:"
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo "2. Edit your OAuth 2.0 Client ID"
echo "3. Add this to Authorized redirect URIs:"
echo "   https://developers.google.com/oauthplayground"
echo "4. Save changes"
echo "5. Then use your credentials in OAuth Playground"
echo ""
echo "But the simple method above is easier and works immediately!"