name: Process Dropzone

on:
  push:
    paths:
      - 'dropzone/**'

permissions:
  contents: write

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run dropzone processor
        run: |
          python -m pip install --upgrade pip
          python mvp/scripts/process_dropzone.py
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "Process dropzone and update data/notes"
            git push
          else
            echo "No changes to commit"
          fi
